version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
    - image: php:7.1-apache
      environment:
        APP_ENV: test
    steps:
    - run:
        name: Install system packages
        command: apt-get update && apt-get -y install git
    - checkout
    - run:
        name: Install Composer
        command: |
          cd wp-content/themes/amineabri/tests
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
    - run:
        name: Display PHP information
        command: |
          php -v
          cd wp-content/themes/amineabri/tests
          php composer.phar --version
    - run:
        name: Install dependencies
        command: |
          cd wp-content/themes/amineabri/tests
          php composer.phar dump-autoload
    - run:
        name: Run Unit tests
        command: |
          cd wp-content/themes/amineabri/tests
          vendor/bin/phpunit --filter testCreateOrder